### ISSUE TITLE
[BUG] Effects Icons/Sidebar disappeared

### ISSUE THREAD

**Issue by MikeyLLP** [NotRyken/AdvancedChatCore#1]
**Effects Icons/Sidebar disappeared**
When i write a Text with AdvancedChat the Effects Icons/Sidebar gets disappeared

**Minecraft Info**
Minecraft information:
- I use the Version 1.21.4(It works also with 1.21.3)
-  I use folow mods Advanchat(Core, HUD, Log, Box)

**To Reproduce**
1. Join on a Server or a World
2. Write a text with AdvanceChat
3. Then u see that the Sidebar or/and the Effect icons Disappear

**Description Video**
https://youtu.be/oOBf8xocDA4

**Comment by NotRyken** [comment]
Thanks for the report. This is actually an issue in AdvancedChatHUD, not AdvancedChatCore. However, it has now been fixed in https://github.com/Arematics/AdvancedChatHUD/commit/33dea06caed4fdacbe17970662dd54579da2961e and the patch has been released as https://github.com/NotRyken/AdvancedChatHUD/releases/tag/v1.3.12

**Comment by NotRyken** [comment]
If you do find any issues in future please check whether they are isolated to one of the sub-mods and if so, open an issue on the relevant repo.
